name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    name: Test Add
    runs-on: ubuntu-latest
    outputs:
      response: ${{ steps.number.outputs.response }}
    steps:
      - name: Github Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Python3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          python -m unittest test_app.py
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app_output
          path: |
            app_output.txt
            app.log
      - name: Save Output
        id: number
        run: |
          echo "response=$(echo 101)" >> $GITHUB_OUTPUT
  deploy:
    name: Deploy App
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Github Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Python3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: app_output
      - name: Output Content
        run: |
          ls
          cat app_output.txt
          echo " Response from test is ${{ needs.test.outputs.response }}"
      - name: Deploy
        run: |
          echo "Deployment done ${{ github.token }}..."